# Generated by Django 6.0.6 on 2026-06-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_emailotp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset', 'Reset Password')], default='register', max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='emailotp',
            constraint=models.UniqueConstraint(fields=('email', 'purpose'), name='unique_email_purpose'),
        ),
    ]
