# Generated by Django 6.0.6 on 2026-07-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Government', 'Government')], default='Citizen', max_length=20),
        ),
    ]
