# Generated by Django 6.0.6 on 2026-06-29 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints_images/')),
                ('voice', models.FileField(blank=True, null=True, upload_to='complaints_voice/')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(blank=True, null=True)),
                ('invalid_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('analysis_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('Roads', 'Roads'), ('Water', 'Water'), ('Electricity', 'Electricity'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Sanitation', 'Sanitation'), ('Environment', 'Environment'), ('Transport', 'Transport'), ('Other', 'Other')], max_length=30)),
                ('priority_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('original_language', models.CharField(blank=True, max_length=30)),
                ('translated_text', models.TextField(blank=True)),
                ('voice_transcript', models.TextField(blank=True)),
                ('suggested_actions', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
