# Generated by Django 6.0.6 on 2026-06-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('ANONYMOUS', 'Anonymous'), ('GOVT ONLY', 'Government Only')], default='PUBLIC', max_length=10),
        ),
    ]
