# Generated by Django 6.0.6 on 2026-06-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('ANONYMOUS', 'Anonymous'), ('GOVT ONLY', 'Government Only')], default='ANONYMOUS', max_length=10),
        ),
    ]
