# Generated by Django 6.0.6 on 2026-07-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='translated_text',
            new_name='english_translation',
        ),
        migrations.AddField(
            model_name='complaint',
            name='severity_reason',
            field=models.TextField(blank=True),
        ),
    ]
