# Generated by Django 6.0.6 on 2026-07-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_rename_translated_text_complaint_english_translation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
