# Generated by Django 6.0.6 on 2026-07-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, choices=[('Road Infrastructure', 'Road Infrastructure'), ('Water', 'Water'), ('Electricity', 'Electricity'), ('Street Lighting', 'Street Lighting'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Sanitation & Garbage', 'Sanitation & Garbage'), ('Environment', 'Environment'), ('Public Transport', 'Public Transport'), ('Public Safety', 'Public Safety'), ('Government Services', 'Government Services'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='visibility',
            field=models.CharField(choices=[('ANONYMOUS', 'Anonymous'), ('GOVT ONLY', 'Government Only')], default='ANONYMOUS', max_length=10),
        ),
    ]
