# Generated by Django 6.0.6 on 2026-07-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_remove_complaint_affected_users_complaintsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsupport',
            name='is_support',
            field=models.BooleanField(default=True),
        ),
    ]
