# Generated by Django 6.0.6 on 2026-07-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaintsupport_is_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintsupport',
            name='is_support',
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_supported',
            field=models.BooleanField(default=False),
        ),
    ]
