# Generated by Django 6.0.6 on 2026-07-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_followed',
            field=models.BooleanField(default=False),
        ),
    ]
