# Generated by Django 6.0.6 on 2026-07-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, choices=[('Road Infrastructure', 'Road Infrastructure'), ('Water', 'Water'), ('Electricity', 'Electricity'), ('Street Lighting', 'Street Lighting'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Sanitation & Garbage', 'Sanitation & Garbage'), ('Environment', 'Environment'), ('Public Transport', 'Public Transport'), ('Public Safety', 'Public Safety'), ('Government Services', 'Government Services'), ('Other', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='is_valid',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='severity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
    ]
