# Generated by Django 6.0.6 on 2026-07-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_alter_complaint_category_alter_complaint_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
