# Generated by Django 6.0.6 on 2026-07-07 09:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='voice_public_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='voice',
            field=models.URLField(blank=True, null=True),
        ),
    ]
