# Generated by Django 6.0.6 on 2026-07-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0017_complaint_voice_public_id_alter_complaint_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='is_valid',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
